ctc-selecao-bolsista/Models/ErrorViewModel.cs
namespace ctc_selecao_bolsista.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ctc-selecao-bolsista/Controllers/AlunoController.cs
using ctc_selecao_bolsista.Data;
using ctc_selecao_bolsista.Data.Entity;
using ctc_selecao_bolsista.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace ctc_selecao_bolsista.Controllers
{
    public class AlunoController : Controller
    {
        private readonly ILogger<AlunoController> _logger;
        public AlunoController(ILogger<AlunoController> logger)
        {
            _logger = logger;
        }

        [Route("")]
        public IActionResult Index()
        {
            return View();
        }

        [Route("Alunos")]
        public IActionResult ListarAlunos()
        {
            List<Aluno> alunos = new List<Aluno>();

            using (var context = new AppDbContext()) 
            {
                alunos = context.Alunos.ToList();
            }

            return View(alunos);
        }

        [Route("Alunos/Formulario")]
        public IActionResult FormularioAluno()
        {
            return View();
        }

        [Route("Alunos/Criar")]
        public IActionResult CriarAluno(Aluno aluno) 
        { 
            
            return RedirectToAction("Index");
        }

        [Route("Alunos/Deletar/{id}")]
        public IActionResult DeletarAluno(int id)
        {
            using (AppDbContext context = new AppDbContext()) 
            {
                Aluno aluno = context.Alunos.Find(id);
                context.Remove(aluno);
                context.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        [Route("Alunos/Atualizar/{id}")]
        public IActionResult AtualizarAluno(int id)
        {
            Aluno aluno = null;
            using(AppDbContext context = new AppDbContext())
            {
                aluno = context.Alunos.Find(id);
            }
            return View("FormularioAluno", aluno);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ctc-selecao-bolsista/Controllers/HomeController.cs
using ctc_selecao_bolsista.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace ctc_selecao_bolsista.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ctc-selecao-bolsista/Views/Aluno/FormularioAluno.cshtml
@{
    ViewData["Title"] = "Formulário aluno";
}
<h1>@ViewData["Title"]</h1>

<div class="container">
    <h2>Cadastro de Aluno</h2>
    <form>
        <div class="form-group">
            <label for="nome">Nome:</label>
            <input type="text" class="form-control" id="nome" required>
        </div>
        <div class="form-group">
            <label for="dataNascimento">Data de Nascimento:</label>
            <input type="date" class="form-control" id="dataNascimento" required>
        </div>
        <div class="form-group">
            <label for="curso">Curso:</label>
            <input type="text" class="form-control" id="curso" required>
        </div>
        <div>
            <br />
            <button type="submit" class="btn btn-primary">Cadastrar</button>
        </div>
    </form>
</div>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

ctc-selecao-bolsista/Views/Aluno/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Bem vindo!</h1>
    <p>Utilize o menu de navegação acima para navegar pelas páginas.</p>
</div>

<div class="container mt-5">
    <h1 class="text-center">Seleção de Bolsistas - Prova Prática</h1>

    <section id="objetivo" class="mt-5">
        <h2>1. Objetivo</h2>
        <p>
            Desenvolver um pequeno sistema para gerenciar alunos utilizando .NET Core no backend, HTML/CSS no frontend
            e SQL Server como banco de dados com o Entity Framework Core como ORM.
        </p>
    </section>

    <section id="especificacoes" class="mt-5">
        <h2>2. Especificações:</h2>

        <h3>2.1 Backend:</h3>
        <p>Desenvolva uma aplicação web em .NET Core.</p>
        <ul>
            <li>Utilize Entity Framework Core como ORM para SQL Server.</li>
            <li>Implemente os métodos do controlador AlunoController para:</li>
            <ul>
                <li>Criar um novo aluno.</li>
                <li>Atualizar um aluno pelo Id.</li>
            </ul>
        </ul>

        <h3>2.2 Frontend:</h3>
        <p>
            Crie uma interface usando HTML e CSS. Você pode optar por usar Angular ou Razor para a criação das
            páginas.
        </p>
        <ul>
            <li>
                <h4>2.2.1 Formulário de Alunos</h4>
                <p>
                    Será usado tanto para cadastro quanto para edição. Se um ID for passado para ele, preencha os
                    campos com as informações do aluno correspondente.
                </p>
                <ul>
                    <li>Deve conter um formulário com os campos: Nome, Data de Nascimento, Curso.</li>
                    <li>Um botão de "Salvar" que envia os dados para a API e salva no banco de dados, tanto para criação quanto para edição.</li>
                </ul>
            </li>
        </ul>

        <h3>2.3 Banco de Dados e Modelo</h3>
        <p>Utilize SQL Server como banco de dados.</p>
    </section>

    <section id="instrucoes" class="mt-5">
        <h2>3. Instruções</h2>
        <ul>
            <li>
                Utilize o projeto disponibilizado no link <a href="https://github.com/alosaulo/selecao-bolsista.git"
                                                             target="_blank">https://github.com/alosaulo/selecao-bolsista.git</a>
            </li>
            <li>Utilize o comando em .net cli <b>dotnet ef database update</b>, ou em Package Manager Console <b>Update-Database</b>, para atualizar o banco de dados.</li>
            <li>Desenvolva o controlador AlunoController com as rotas especificadas.</li>
            <li>Crie o frontend com o "Formulário de Alunos" e a página de listagem.</li>
            <li>Certifique-se de que todas as operações do CRUD estejam funcionando corretamente.</li>
            <li>Enviar o projeto comprimido para o email: saulocaliman@ceet.secti.es.gov.br</li>

        </ul>
    </section>

    <section id="criterios" class="mt-5">
        <h2>4. Critérios de Avaliação:</h2>
        <ul>
            <li>Funcionalidade: Todas as operações do CRUD devem estar funcionais.</li>
            <li>Design: A interface, mesmo simples, deve ser limpa e intuitiva. Modificar a interface padrão é um diferencial.</li>
            <li>Organização do Código: O código deve ser bem estruturado e seguir boas práticas.</li>
            <li>Interação com o Banco: O uso correto do Entity Framework Core com SQL Server será avaliado.</li>
            <li>Feedback para o Usuário: O sistema deve fornecer feedbacks claros após cada operação.</li>
        </ul>
    </section>

    <section id="observacoes" class="mt-5 mb-5">
        <h2>5. Observações:</h2>
        <p>A escolha de bibliotecas adicionais é livre. Justifique suas escolhas se perguntado.</p>
        <p>A avaliação é focada em habilidades técnicas, solução de problemas e organização.</p>
        <p>Boa sorte!</p>
    </section>
</div>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.2/js/bootstrap.bundle.min.js"></script>

ctc-selecao-bolsista/Views/Aluno/ListarAlunos.cshtml
@using ctc_selecao_bolsista.Data.Entity

@model List<Aluno>

@{
    ViewData["Title"] = "Alunos";
}
<h1>@ViewData["Title"]</h1>


<div class="container">
    <h2>Tabela de Alunos</h2>
    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nome</th>
                <th>Data de Nascimento</th>
                <th>Curso</th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>
            <!-- Uma linha exemplo -->
            @foreach (Aluno aluno in Model)
            {
                <tr>
                    <td>@aluno.alunoId</td>
                    <td>@aluno.Nome</td>
                    <td>@aluno.DataNascimento.ToShortDateString()</td>
                    <td>@aluno.Curso</td>
                    <td>
                        <a asp-controller="Aluno" asp-action="AtualizarAluno" asp-route-id='@aluno.alunoId' class="btn btn-primary">Atualizar</a>
                        <a asp-controller="Aluno" asp-action="DeletarAluno" asp-route-id='@aluno.alunoId' class="btn btn-danger" onclick="confirm(' Você tem certeza que deseja deletar este aluno?');">Deletar</a>
                    </td>
                </tr>
            }
            <!-- Adicione mais linhas conforme necessário -->
        </tbody>
    </table>
    <p>Total: @Model.Count alunos</p>
</div>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

ctc-selecao-bolsista/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CTC SELEÇÃO BOLSISTA</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ctc_selecao_bolsista.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Aluno" asp-action="Index">CTC SELEÇÃO BOLSISTA</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Aluno" asp-action="ListarAlunos">Mostrar Alunos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Aluno" asp-action="FormularioAluno">Cadastrar Aluno</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - CTC SELEÇÃO BOLSISTA </a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>